/**
 * \file DCL.C
 *
 * \note As written, these tests catch template declarations only if
 * instantiated.
 *
 * Copyright (c) 2007 Carnegie Mellon University.
 * All rights reserved.

 * Permission to use this software and its documentation for any purpose is
 * hereby granted, provided that the above copyright notice appear and that
 * both that copyright notice and this permission notice appear in supporting
 * documentation, and that the name of CMU not be used in advertising or
 * publicity pertaining to distribution of the software without specific,
 * written prior permission.
 *
 * CMU DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
 * IMPLIED WSTRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL CMU BE
 * LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, RISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include "rose.h"
#include "utilities.h"

/**
 * Const-qualify immutable objects
 *
 * \todo count assignments, if only one, report violation
 */
bool DCL00_A( const SgNode *node ) {
	const SgInitializedName *varName = isSgInitializedName(node);
	if (!varName)
		return false;

	/**
	 * Ignore variables generated by macros
	 */
	if (varName->get_name().getString().substr(0,2) == "__")
		return false;

	/**
	 * Ignore variables that are already const, are function pointers, or are
	 * declared inside of a struct, enum, or as an argument to a function
	 */
	Type varType(varName->get_type());
	if (varType.isConst()
	|| varType.dereference().isConst()
	|| varType.isFunction()
	|| findParentNodeOfType(varName, V_SgEnumDeclaration).first
	|| findParentNodeOfType(varName, V_SgClassDeclaration).first
	|| findParentNodeOfType(varName, V_SgFunctionParameterList).first)
		return false;

	/**
	 * Ignore global variables or variables declared as extern
	 */
	const SgScopeStatement *varScope = varName->get_scope();
	if (isSgGlobal(varScope)
	|| const_cast<SgInitializedName*>(varName)->get_storageModifier().isExtern())
		return false;

	FOREACH_SUBNODE(varScope, nodes, i, V_SgVarRefExp) {
		const SgVarRefExp *iVar = isSgVarRefExp(*i);
		assert(iVar);
		if (getRefDecl(iVar) != varName)
			continue;

		const SgNode *parent = iVar->get_parent();
		assert(parent);

		/**
		 * If the variable is written to or it's address is taken, we can no
		 * longer be sure it should be const, if it's a struct and gets
		 * dereferenced, who knows what's getting written there :/
		 *
		 * \todo Is this address thing correct?
		 */
		if (varWrittenTo(iVar)
		||  isSgArrowExp(parent)
		||  findParentNodeOfType(iVar, V_SgAddressOfOp).first)
			return false;

		/**
		 * If the variable is a pointer or array, and we pass it to a function
		 * or as an argument to pointer arithmetic, or assign it's value
		 * somewhere, we can longer be sure it should be const
		 */
		if ((varType.isPointer() || varType.isArray())
		&& (findParentNodeOfType(iVar, V_SgFunctionCallExp).first
			|| isSgAddOp(parent)
			|| isSgSubtractOp(parent)
			|| isSgAssignOp(parent)
			|| isSgPntrArrRefExp(parent)
			|| isSgPointerDerefExp(parent)
			|| isSgAssignInitializer(parent)))
			return false;
	}

	const std::string msg = "Const-qualify immutable objects: " + varName->unparseToString();
	print_error(node, "DCL00-A", msg.c_str(), true);
	return true;
}

/**
 * Do not reuse variable names in subscopes
 */
bool DCL01_A( const SgNode *node ) {
	const SgInitializedName *varInitName = isSgInitializedName(node);
	if (!varInitName)
		return false;
	const SgName varName = varInitName->get_name();
	const SgScopeStatement *varScope = varInitName->get_scope();
	assert(varScope);
	while(!isSgGlobal(varScope)) {
		varScope = varScope->get_scope();
		if(varScope->symbol_exists(varName)) {
			print_error(node, "DCL01-A", "Do not reuse variable names in subscopes", true);
			return true;
		}
	}

	return false;
}

/**
 * Do not declare an identifier with conflicting linkage classifications
 *
 * \note GCC catches this
 */
bool DCL36_C( const SgNode *node ) {
	return false;
}

bool DCL(const SgNode *node) {
  bool violation = false;
  violation |= DCL00_A(node);
  violation |= DCL01_A(node);
  return violation;
}
